### ISSUE TITLE
Oxid 4.10.3 not available

### ISSUE THREAD

**Issue by sphr2k** [marcharding/oxrun#12]
Hi,

I tried installing the latest OXID CE version 4.10.3 using 

oxrun install:shop --oxidVersion="4.10.3" [...]

but this produces the following error:

"Oxid 4.10.3 not available"

The tarball for 4.10.3 is correctly referenced in https://api.github.com/repos/OXID-eSales/oxideshop_ce/tags

Thanks,
Jan

**Comment by marcharding** [comment]
Sadly the installer is not included in the news tarballs, so i'll have to rewrite that part of oxrun.

edit: forget that, just the folder structure has changed, should be fixable.

**Comment by marcharding** [comment]
Fixed in latest release.
