### ISSUE TITLE
Forget to create new oxrun.phar 

### ISSUE THREAD

**Issue by tmloberon** [marcharding/oxrun#26]
In master-branch is a old Version of oxrun.phar. That need to be renewed. I do not dare to renew it. Because I do not know which version should be deposited: v1.0.0 or v2.0.0.

**Comment by marcharding** [comment]
I'd like to include the phar building process into travis (when a tag is pushed) and then automatically but it into the releases tab. What do you think about that?

As for the version, a clean start with 2.0.0 sounds okay.

**Comment by tmloberon** [comment]
Yes that is cool!

**Comment by marcharding** [comment]
Done 🎉
