### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [marcharding/oxrun#30]
Hi, what is the current status of this project?

**Comment by adriankirchner** [comment]
Hi Daniel, the project moved to https://github.com/OXIDprojects/oxrun and is still.

**Comment by DanielRuf** [comment]
Well, would be great to have the issues tab there.

**Comment by adriankirchner** [comment]
Maybe @tmloberon can do something about that.

**Comment by TumTum** [comment]
Ahh sure ... now it is enable to write issue to the oxidprojects repo. This repo from marcharding is for OXID < v4.10 and the oxidproject/oxrun is for OXID >v6.
