### ISSUE TITLE
Only install:shop command available

### ISSUE THREAD

**Issue by ssachtleben** [marcharding/oxrun#4]
Hey,

nice CLI. But I cant get any other command running than install:shop. For example I want to set a config:

oxrun config:set

  [InvalidArgumentException]
  There are no commands defined in the "config" namespace.

Is there something I missed?

oxrun list gives me:

oxrun version dev-master

Usage:
  command [options] [arguments]

Options:
  -h, --help               Display this help message
  -q, --quiet              Do not output any message
  -V, --version            Display this application version
      --ansi               Force ANSI output
      --no-ansi            Disable ANSI output
  -n, --no-interaction     Do not ask any interactive question
      --shopDir[=SHOPDIR]  Force oxid base dir. No auto detection
  -v|vv|vvv, --verbose     Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help          Displays help for a command
  list          Lists commands
 install
  install:shop  Installs the shop

**Comment by ssachtleben** [comment]
ah ok solved it by adding the shop dir:
oxrun --shopDir=/var/www/oxid/ list

**Comment by marcharding** [comment]
Oxrun needs to be executed from inside the shop base dir or with the provided --shopDir parameter (as you just did).

I would recommend putting the phar-file into your PATH-Variable for convenience and then just call it from the shop base dir.

**Comment by ssachtleben** [comment]
@marcharding Ok thanks. Is config:set working for you with the lastest oxid version? It says settings x to y but value is empty in admin module settings :(

**Comment by marcharding** [comment]
Could you please open a new issue and specify which value you try to set (paste the executed line)?

**Comment by ssachtleben** [comment]
thanks I solved it. I missed the moduleId so I had to do this:

oxrun --shopDir=/var/www/oxid/ config:set --variableType=str --moduleId=module:Test name value

:smile:
