### ISSUE TITLE
Oxrun exceeds Github rate limit

### ISSUE THREAD

**Issue by schnubor** [marcharding/oxrun#5]
Hi,

now this isn't really critical at all, but while setting up my server which is using oxrun I noticed that it's obviously also calling `https://api.github.com/repos/OXID-eSales/oxideshop_ce/tags` at at least one point. Now while provisioning my server over and over again I suddenly hit the rate limit of Githubs API. This could be prevented when providing a clientid and secret with the request (see https://developer.github.com/v3/#rate-limiting). 

Is this something that can be configured? If not, I guess it would be useful.

Best regards,

Christian

**Comment by robinlehrmann** [comment]
Hi,

> Am 18.02.2016 um 17:16 schrieb Christian Korndörfer notifications@github.com:
> Is this something that can be configured? If not, I guess it would be useful.
> 
> you can create an api token in your github account. See: https://github.com/settings/tokens/new https://github.com/settings/tokens/new

Now you should paste your newly created token in the auth.son in your COMPOSER_HOME dir (default is the home directory on an unix system)

execute:

echo '{"github-oauth": {"github.com": „ACCESS-TOKEN-HERE“}}' > ~/.composer/auth.json“

now you can pull your composer dependencies with composer update or composer install.

Cheers,
Robin

**Comment by marcharding** [comment]
Hi,

this won't work since the download is independed from composer, maybe i should add a default search for a auth.json...

But you can set an env variable named GITHUB_TOKEN with your token and everything should be fine, see https://github.com/marcharding/oxrun/blob/master/src/Oxrun/Command/Install/InstallCommand.php#L190

`export GITHUB_TOKEN="YOURTOKEN"`

Let me know if it works.

Marc.

**Comment by schnubor** [comment]
Hi @marcharding ,

sorry for the late response. I created a personal access token (https://help.github.com/articles/creating-an-access-token-for-command-line-use/) and set in for each shell command. It's appending the access_token to the requests correctly but now I get a 401 (instead of a 403) response. Heres the full error message (replaced my real token with <my_token>)

```
Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.github.com/repos/OXID-eSales/oxideshop_ce/tags?access_token=<my_token> [status code] 401 [reason phrase] Unauthorized' in phar:///usr/local/bin/oxrun/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:2
```

Any ideas about that?

Best regards,
Christian

**Comment by schnubor** [comment]
Hi Marc,

thanks for the advice and sorry for the late answer! exporting the ENV var works fine :+1: 
This solves the issue for me so I'm closing it.

Best regards,
Christian
